language: csharp
solution: PerformSys.sln
install:
  - nuget restore PerformSys.sln
script:
  - xbuild /p:Configuration=Release PerformSys.sln
  - VERSION="1.1.1"
  - TAG="PerformSys-${VERSION}"
  - FILENAME="${TAG}.tgz"
  - cp -rf Utils/*.bat bin/Release/
  - tar -czf ${FILENAME} -C bin/Release/ . --exclude='*.pdb' --exclude='*.xml' --exclude='*.mdb' 
before_deploy:
  - git config --local user.name "builder"
  - git config --local user.email "builder@travis-ci.com"
  - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
deploy:
  provider: releases
  api_key: ${APIKEY}
  file: ${FILENAME}
  skip_cleanup: true