//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18449
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace client.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("client.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на select
        ///	l_returnflag,
        ///	l_linestatus,
        ///	sum(l_quantity) as sum_qty,
        ///	sum(l_extendedprice) as sum_base_price,
        ///	sum(l_extendedprice * (1 - l_discount)) as sum_disc_price,
        ///	sum(l_extendedprice * (1 - l_discount) * (1 + l_tax)) as sum_charge,
        ///	avg(l_quantity) as avg_qty,
        ///	avg(l_extendedprice) as avg_price,
        ///	avg(l_discount) as avg_disc,
        ///	count(*) as count_order
        ///from
        ///	lineitem
        ///where
        ///	l_shipdate &lt;= date &apos;1998-12-01&apos; - interval &apos;105&apos; day (3)
        ///group by
        ///	l_returnflag,
        ///	l_linestatus
        ///order by
        ///	l_returnf [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string q1 {
            get {
                return ResourceManager.GetString("q1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на select
        ///	s_acctbal,
        ///	s_name,
        ///	n_name,
        ///	p_partkey,
        ///	p_mfgr,
        ///	s_address,
        ///	s_phone,
        ///	s_comment
        ///from
        ///	part,
        ///	supplier,
        ///	partsupp,
        ///	nation,
        ///	region
        ///where
        ///	p_partkey = ps_partkey
        ///	and s_suppkey = ps_suppkey
        ///	and p_size = 48
        ///	and p_type like &apos;%NICKEL&apos;
        ///	and s_nationkey = n_nationkey
        ///	and n_regionkey = r_regionkey
        ///	and r_name = &apos;AMERICA&apos;
        ///	and ps_supplycost = (
        ///		select
        ///			min(ps_supplycost)
        ///		from
        ///			partsupp,
        ///			supplier,
        ///			nation,
        ///			region
        ///		where
        ///			p_partkey = ps_partkey
        ///			and  [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string q2 {
            get {
                return ResourceManager.GetString("q2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на select
        ///	l_orderkey,
        ///	sum(l_extendedprice * (1 - l_discount)) as revenue,
        ///	o_orderdate,
        ///	o_shippriority
        ///from
        ///	customer,
        ///	orders,
        ///	lineitem
        ///where
        ///	c_mktsegment = &apos;HOUSEHOLD&apos;
        ///	and c_custkey = o_custkey
        ///	and l_orderkey = o_orderkey
        ///	and o_orderdate &lt; date &apos;1995-03-31&apos;
        ///	and l_shipdate &gt; date &apos;1995-03-31&apos;
        ///group by
        ///	l_orderkey,
        ///	o_orderdate,
        ///	o_shippriority
        ///order by
        ///	revenue desc,
        ///	o_orderdate
        ///limit 0,10;
        ///
        ///.
        /// </summary>
        internal static string q3 {
            get {
                return ResourceManager.GetString("q3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на select
        ///	o_orderpriority,
        ///	count(*) as order_count
        ///from
        ///	orders
        ///where
        ///	o_orderdate &gt;= date &apos;1996-02-01&apos;
        ///	and o_orderdate &lt; date &apos;1996-02-01&apos; + interval &apos;3&apos; month
        ///	and exists (
        ///		select
        ///			*
        ///		from
        ///			lineitem
        ///		where
        ///			l_orderkey = o_orderkey
        ///			and l_commitdate &lt; l_receiptdate
        ///	)
        ///group by
        ///	o_orderpriority
        ///order by
        ///	o_orderpriority;
        ///
        ///.
        /// </summary>
        internal static string q4 {
            get {
                return ResourceManager.GetString("q4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на select
        ///	n_name,
        ///	sum(l_extendedprice * (1 - l_discount)) as revenue
        ///from
        ///	customer,
        ///	orders,
        ///	lineitem,
        ///	supplier,
        ///	nation,
        ///	region
        ///where
        ///	c_custkey = o_custkey
        ///	and l_orderkey = o_orderkey
        ///	and l_suppkey = s_suppkey
        ///	and c_nationkey = s_nationkey
        ///	and s_nationkey = n_nationkey
        ///	and n_regionkey = r_regionkey
        ///	and r_name = &apos;MIDDLE EAST&apos;
        ///	and o_orderdate &gt;= date &apos;1995-01-01&apos;
        ///	and o_orderdate &lt; date &apos;1995-01-01&apos; + interval &apos;1&apos; year
        ///group by
        ///	n_name
        ///order by
        ///	revenue desc;
        ///
        ///.
        /// </summary>
        internal static string q5 {
            get {
                return ResourceManager.GetString("q5", resourceCulture);
            }
        }
    }
}
